---
abstract: 'Lightweight To-The-Point Email'
author:
  - 'Al Newkirk <anewkirk@ana.io>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300034, CPAN::Meta::Converter version 2.130880'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Emailesque
requires:
  Authen::SASL: 0
  Email::AddressParser: 1
  Email::Stuffer: 0
  Hash::Merge: 0.12
  IO::Socket::SSL: 0
  Net::SMTP::SSL: 0
  Net::SMTP::TLS: 0
  Net::SSLeay: 0
resources:
  bugtracker: https://github.com/alnewkirk/Emailesque/issues
  homepage: http://search.cpan.org/dist/Emailesque/
  repository: git://github.com/alnewkirk/Emailesque.git
version: 1.200001
