---
abstract: 'Lightweight To-The-Point Email'
author:
  - 'Al Newkirk <awncorp@cpan.org>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.31
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.102342, CPAN::Meta::Converter version 2.102400'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Emailesque
requires:
  Authen::SASL: 0
  Email::AddressParser: 1
  Email::Stuff: 2.102
  Hash::Merge: 0.12
  IO::Socket::SSL: 0
  Net::SMTP::SSL: 0
  Net::SMTP::TLS: 0
  Net::SSLeay: 0
version: 1.110220
